version: '3.1'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: todo_app
      POSTGRES_USER: todo_user
      POSTGRES_DB: todo_db