version: '3.1'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: todo_app
      POSTGRES_USER: todo_user
      POSTGRES_DB: todo_db
    ports:
      - 5432:5432